### ISSUE TITLE
Integrity checksum failed when using sha512

### ISSUE THREAD

**Issue by avitorio** [iamraphson/adonisjs-hackathon-starter#10]
ERROR  Command failed: npm install
npm ERR! code EINTEGRITY
npm ERR! sha512-lzTiSnWjy9ygJO1/Sm8FBnlx9at/vDsNLO/gQ15cVZAv5IeuGdADGh0Q8D0vQl45pWrG1kHtdGfGQyyatZ2cmg== integrity checksum failed when using sha512: wanted sha512-lzTiSnWjy9ygJO1/Sm8FBnlx9at/vDsNLO/gQ15cVZAv5IeuGdADGh0Q8D0vQl45pWrG1kHtdGfGQyyatZ2cmg== but got sha512-W1oSBVjGBcjH97Cu4zNZWKHFM7tj9NPSbxfylyvnwK/+y51bAWtvOH6/VWDi9Om3DSUGXvVGX66qRYffiNIYCw==. (5144 bytes)

**Comment by iamraphson** [comment]
Hey @avitorio kindly try this https://stackoverflow.com/questions/47545940/when-i-run-npm-install-it-returns-with-err-code-eintegrity-npm-5-3-0/47922056

**Comment by avitorio** [comment]
@iamraphson Thank you!
