### ISSUE TITLE
Ready for AdonisJS 4.0, yay!

### ISSUE THREAD

**Issue by Maxximus007** [iamraphson/adonisjs-hackathon-starter#2]
Hi,

Was already following your starter, and saw you have updated it for 4.0, thank you!

Some small references to 3.2 in the readme, you might want to change this.

Was wondering if it's still needed to use your Ally, and not the official one? Another small thing: node-uuid gives a warning, perhaps uuid package can replace it?

Do you have planned to replace Bootstrap with 4.0?  

Another addition could be Mo0x/Pjax, works nicely with Edge.

Regards.

PS: In the readme you refer to a Laravel key generator, better use `adonis key:generate`

PPS: Perhaps it's possible to convert it to an Adonis blueprint?

**Comment by iamraphson** [comment]
@Maxximus007 Thanks, A lot

You can use any of the ally but bit-bucket login will not work with the official one because My PR is yet to be merged https://github.com/adonisjs/adonis-ally/pull/10 as soon as it is merged will upgrade it to the official one

what warning is `node-uuid` giving? Can you explain better? 

Nice  Idea. I will look into bootstrap 4 and upgrade it nevertheless your PR can be welcome 😌? 

what did you mean as Adonis BluePrint? 

PS: I have updated the readme

**Comment by Maxximus007** [comment]
Thanks for your fast reply!

About blueprint: According to AdonisJS doc you can start new project with community based template: 
_To make use of community created blueprints, you can pass --blueprint=<github-org/repo>._
So no git clone needed, install with Adonis directly. Just tried it with your starter, works nicely! 
So you don't have to do anything with the code, just mention it in the readme perhaps.

Will try to upgrade to BS 4, and when done inform you!

Keep up the good work!

Edit: Small issue: The name field in package.json must not contain spaces (yarn will error). Uppercase seems to be discouraged, so: adonisjs-hackathon-starter

About node-uuid: this is the warning:
`warning node-uuid@1.4.8: Use uuid module instead `

**Comment by iamraphson** [comment]
@Maxximus007 Thanks,  A lot for your observation. 
can you give me the command line for the blueprint? 
I have fixed the name field in the package.json
for the `node-uuid` package, I have replaced it with https://www.npmjs.com/package/rand-token

**Comment by Maxximus007** [comment]
@iamraphson great!
The command line is: `adonis new yardstick --blueprint=iamraphson/adonisjs-hackathon-starter`
Works like a charm now! .env.example is copied to .env, a new appkey is generated.

Only need to set DB info and run migrations. It might be an idea to use SQLite as the default, makes it even easier 'out of the box'.

Your Starter has the potential to become the preferred AdonisJS blueprint IMHO, and help grow the community!

**Comment by iamraphson** [comment]
@Maxximus007 thanks, A lot

You can change the DB default connection if you want. When I was developing it, I used MySQL, when deploying it on Heroku, I used PostgreSQL. So the starter can work with any DB.

**Comment by Maxximus007** [comment]
Yes, I'm personally happy with that. Cirrently in the .env file MySQL is the chosen DB, so someone using the blueprint needs to set up a MySQL DB, or change it in .env to 'sqlite' and install npm package (not yet in package.json). 
I just mentioned it to make the installation for first time users as painless as possible, since a new environment can be quite overwhelming.

**Comment by iamraphson** [comment]
@Maxximus007 I think I will add `sqlite` to package.json and update my `.env.example` file

**Comment by Maxximus007** [comment]
Unrelated, but just cleaned up and installed a fresh copy. Logging in with Google seems to work fine, but on the console I see this:
`1st error  InvalidSessionException: E_INVALID_SESSION: Invalid session
    at Function.invoke (/node_modules/@adonisjs/auth/src/Exceptions/index.js:200:12)
    at SessionScheme.check (/node_modules/@adonisjs/auth/src/Schemes/Session.js:275:38)
    at AuthController.handleProviderCallback (/app/Controllers/Http/Auth/AuthController.js:85:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`
Didn't see it before..
Line 85 in AuthController is: `await auth.check()`
Is it related to the issue mentioned in the forum? Running with Chrome here. Session is set to cookie, and sameSite: false.

**Comment by iamraphson** [comment]
@Maxximus007 it's the issue. Twitter and Google login was not going on chrome. I will remove the log. but it's working

**Comment by iamraphson** [comment]
@Maxximus007 I have added it.

**Comment by Maxximus007** [comment]
Great! I'm working to update with Bootstrap 4 Beta, will be my first PR so please be patient ;)

**Comment by iamraphson** [comment]
@Maxximus007 thanks a lot. 🙌🙌

**Comment by Maxximus007** [comment]
@iamraphson have made a PR for BS 4 for review ready.

**Comment by iamraphson** [comment]
@Maxximus007 PR merged...Thanks

**Comment by Maxximus007** [comment]
@iamraphson Thanks for accepting! You might want to mention your blueprint as showcase in the forum? One thing to consider is a backend / admin, that would make a jumpstart really complete. this looks nice https://github.com/mrholek/CoreUI-Free-Bootstrap-Admin-Template, but will need some work to make it Edge ready. Or maybe consider the Vue version?

**Comment by iamraphson** [comment]
@Maxximus007 I will see to it soon.

**Comment by Maxximus007** [comment]
Hi, since Adonis 4.0 has the blueprint flag, you might want to replace the 'Getting started' chapter with something like this:

If you have set up the prerequisites, you're up and running in no time:
```
npm i -g @adonisjs/cli

adonis new starter --blueprint=iamraphson/adonisjs-hackathon-starter

# Run migrations
adonis migration:run

adonis serve --dev
```
That's it! All you have to do now is retrieve the desired API keys, and add these to the .env file.

**Comment by iamraphson** [comment]
@Maxximus007 done
