### ISSUE TITLE
Can't upload avatar image.

### ISSUE THREAD

**Issue by amitkhare** [iamraphson/adonisjs-hackathon-starter#6]
**Error in console:**

{ message: 'Missing required parameter - file', http_code: 400 }

**Comment by amitkhare** [comment]
Fixed it.
Just change **AccountController.js** at line **~63**
const cloudinaryResponse = await users.uploadToCloudinary(profilePic.**_tmpPath**)

to

const cloudinaryResponse = await users.uploadToCloudinary(profilePic.**tmpPath**)

**Comment by iamraphson** [comment]
@amitkhare thanks. Fixed from my end.
